version: '3.1'
services:
  load-balancer:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    links:
      - web

  web:
    build: ./server
    environment:
      DB_HOST: db
    links:
      - db

  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DATABASE: root
    ports:
      - 5432:5432
